name: Announcements
on:
  release:
    types: [published]

jobs:
  synthesis:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Discord Notification"
        run: |
            curl \
            -H "Content-Type: application/json" \
            -d '{
                "username": "mattpannella",
                "avatar_url": "https://avatars.githubusercontent.com/u/4806679",
                "content": "Pocket Updater Utility Release",
                "embeds": [{
                    "color": 4819409,
                    "title": "${{ github.event.release.name }}",
                    "fields": [
                        { "name": "Release Notes", "value": "[Click Me](https://github.com/mattpannella/pocket-updater-utility/releases/tag/${{ github.event.release.tag_name }})", "inline": true },
                        { "name": "Version", "value": "${{ github.event.release.tag_name }}", "inline": true },
                        { "name": "macOS Build", "value": "[Download Me](https://github.com/mattpannella/pocket-updater-utility/releases/download/${{ github.event.release.tag_name }}/pocket_updater_mac.zip)" },
                        { "name": "Linux Build", "value": "[Or Me](https://github.com/mattpannella/pocket-updater-utility/releases/download/${{ github.event.release.tag_name }}/pocket_updater_linux.zip)" },
                        { "name": "Linux ARM64 Build", "value": "[This is for creeps](https://github.com/mattpannella/pocket-updater-utility/releases/download/${{ github.event.release.tag_name }}/pocket_updater_linux_arm.zip)" },
                        { "name": "Windows Build", "value": "[This is a virus](https://github.com/mattpannella/pocket-updater-utility/releases/download/${{ github.event.release.tag_name }}/pocket_updater_win.zip)" }
                    ]
                }]
                }' \
            ${{ secrets.DISCORD_WEBHOOK }}
